plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "build"
command = "npm run build"
build="build"
commandOrigin = "heuristics"

[build.environment]
NODE_VERSION="20.11.1"
NPM_VERSION="10.2.4"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]