# Branch-specific settings for "play" branch
[context.play]  # Use the branch name as the context identifier
  publish = "."  # Specify the directory to publish for this branch
  command = "echo 'nuh uh'"