# Branch-specific settings for "play" branch
[[context]]
  branch = "play"  # Specify the branch name

  # No build command is specified, so no build process will be triggered
  # You only need to specify the publish directory
  publish = "."  # Assuming the static HTML code is located in the root directory of the "play" branch
